version: "3"
services:
  web_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hips
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DEBUG=true
    ports:
      - "8080:8000"